# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Mood"
license = "MIT"
licenselink = "https://github.com/harrycresswell/mood/blob/main/LICENSE"
description = "A  personal moodboard theme for visual inspiration"
homepage = "https://github.com/harrycresswell/mood/"
tags = ["minimal", "simple", "moodboard", "gallery", "responsive", "mobile" ]
features = ["Cloudinary images", "Low quality Image placeholders", "Next-gen image formats"]
min_version = "0.92.2"

[author]
  name = "Harry Cresswell"
  homepage = "https://harrycresswell.com/"
  github = "https://github.com/harrycresswell/"

# If porting an existing theme
[original]
  author = "Harry Cresswell"
  homepage = "https://harrycresswell.com/"
  repo = "https://github.com/harrycresswell/mood/"
