[context.production.environment]
  HUGO_VERSION = "0.92.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.92.2"

[build]
  publish = "public"
  command = "hugo --gc --minify"

# Cloudinary
[[redirects]]
from = "/images/:format/:quality/:width/*"
to = "https://res.cloudinary.com/harrycresswell/image/upload/:format/:quality/:width/:splat"
status = 200

# Netlify Headers
[[headers]]
  for = "/images/*"
  [headers.values]
    # Cache for one year
    Cache-Control = "public, max-age=31536000, immutable"